// End-to-end coverage for the Grid Code Viewer upload → extract → re-index
// flow and the user-facing error handling added in the hardening pass.
// Drives a real browser against real files, the way a user would.

import { test, expect, type Page } from '@playwright/test';
import path from 'node:path';

// A small valid PDF (committed fixture) whose headings use real grid-code
// clause IDs, so extraction produces both clause→page hits and outline rows.
// Generated by tests/fixtures/make-sample-pdf.mjs.
const VALID_PDF = path.join(process.cwd(), 'tests', 'fixtures', 'grid-code-sample.pdf');

// A file that *looks* like a PDF (".pdf" name) but is actually HTML — the
// shape of "user grabbed the wrong download". PDF.js rejects it, which must
// surface to the user rather than failing silently.
const NOT_A_PDF = path.join(process.cwd(), 'tests', 'fixtures', 'not-a-pdf.pdf');

const VIEWER = '/tools/grid-code-viewer/?doc=grid-code&view=viewer';

// Read the persisted local-copy record straight from IndexedDB — the ground
// truth for "did extraction run and persist".
async function readRecord(page: Page) {
  return page.evaluate(async () => {
    const db: IDBDatabase = await new Promise((res, rej) => {
      const r = indexedDB.open('eee-grid-code', 1);
      r.onsuccess = () => res(r.result);
      r.onerror = () => rej(r.error);
    });
    const rec = await new Promise<Record<string, unknown> | undefined>((res, rej) => {
      const req = db.transaction('local-pdfs', 'readonly').objectStore('local-pdfs').get('grid-code');
      req.onsuccess = () => res(req.result);
      req.onerror = () => rej(req.error);
    });
    db.close();
    return rec ?? null;
  });
}

test.describe('Grid Code Viewer — upload, extraction, re-index', () => {
  test('uploads a valid PDF, renders it, and runs extraction to completion', async ({ page }) => {
    test.setTimeout(90_000);
    const pageErrors: string[] = [];
    page.on('pageerror', e => pageErrors.push(String(e)));

    await page.goto(VIEWER);
    await expect(page.locator('.ud-root')).toBeVisible({ timeout: 15_000 }); // link-only → dropzone

    await page.setInputFiles('.ud-root input[type="file"]', VALID_PDF);

    // View switches to the split pane and renders the PDF via PDF.js.
    await expect(page.locator('.vsp-split')).toBeVisible({ timeout: 15_000 });
    await expect(page.locator('.vsp-split iframe')).toBeVisible({ timeout: 15_000 });
    await expect(page.locator('.vsp-local-badge')).toBeVisible(); // blob stored in IndexedDB

    // Ground truth: the indexing pipeline stamps EXTRACTOR_VERSION (3) only on
    // full success, so polling for it proves both phases ran end-to-end.
    await expect
      .poll(async () => (await readRecord(page))?.extractorVersion ?? 0,
            { timeout: 60_000, message: 'extractor version never stamped' })
      .toBe(3);

    const rec = await readRecord(page);
    const outline = Array.isArray(rec?.outline) ? (rec!.outline as Array<{ id: string }>) : [];
    const clausePages = (rec?.clausePages ?? {}) as Record<string, number>;
    console.log(`[e2e] extraction persisted: outline=${outline.length} clausePages=${JSON.stringify(clausePages)}`);

    // Real extraction output: the fixture's clause IDs were located on their
    // pages, and the heading tier produced outline rows.
    expect(clausePages['ECC.6.3.7']).toBeGreaterThan(0);
    expect(outline.length).toBeGreaterThan(0);

    // The OUTLINE tab is populated (curated grid-code clauses + extracted rows).
    await page.getByRole('tab', { name: /Outline/ }).click();
    await expect(page.locator('.rcp-list--outline .rcp-edge').first()).toBeVisible();

    // A clean run shows no error toast and throws no uncaught errors.
    await expect(page.locator('.app-toast--error')).toHaveCount(0);
    expect(pageErrors, pageErrors.join('\n')).toEqual([]);
  });

  test('shows an error toast when the uploaded file is not a real PDF', async ({ page }) => {
    test.setTimeout(60_000);
    await page.goto(VIEWER);
    await expect(page.locator('.ud-root')).toBeVisible({ timeout: 15_000 });

    // nc-dcc.pdf is actually HTML → PDF.js throws → indexing rejects.
    await page.setInputFiles('.ud-root input[type="file"]', NOT_A_PDF);

    const toast = page.locator('.app-toast--error');
    await expect(toast).toBeVisible({ timeout: 20_000 });
    // Either the upload-path or the auto-reindex-path message is acceptable —
    // both are the hardening's new user-facing signal (was console-only before).
    await expect(toast).toContainText(/indexing failed|couldn’t refresh|re-index failed/i);
  });

  test('shows an error toast when a manual re-index fails', async ({ page }) => {
    test.setTimeout(60_000);
    // Break the extractor's PDF.js load from the start. storeLocalPdf still
    // succeeds (creating the local copy); every extraction — including the
    // manual re-index — rejects (loadPdfJs memoises the failed import).
    await page.route('**/pdfjs/build/pdf.mjs', route => route.abort());

    await page.goto(VIEWER);
    await expect(page.locator('.ud-root')).toBeVisible({ timeout: 15_000 });
    await page.setInputFiles('.ud-root input[type="file"]', VALID_PDF);

    await expect(page.locator('.vsp-local-badge')).toBeVisible({ timeout: 15_000 });
    await expect(page.locator('.app-toast--error')).toBeVisible({ timeout: 20_000 });
    await page.waitForTimeout(3500); // let the first toast auto-dismiss

    await page.getByRole('button', { name: /^Re-index$/ }).click();
    const toast = page.locator('.app-toast--error');
    await expect(toast).toBeVisible({ timeout: 20_000 });
    await expect(toast).toContainText(/Re-index failed/i);
  });
});
