import { existsSync, readFileSync, writeFileSync } from 'fs';
import { mkdir, rm } from 'fs/promises';
import { execSync } from 'child_process';
import { tmpdir } from 'os';
import { join } from 'path';

const PDFJS_VERSION = '5.4.449';
const PDFJS_DIR     = 'public/pdfjs';
const WEB_DIR       = join(PDFJS_DIR, 'web');
const VIEWER_HTML   = join(WEB_DIR, 'viewer.html');
const VIEWER_INDEX_DIR  = join(WEB_DIR, 'viewer');
const VIEWER_INDEX_HTML = join(VIEWER_INDEX_DIR, 'index.html');
const TEMP_ZIP      = join(tmpdir(), 'pdfjs.zip');
const isWindows = process.platform === 'win32';

async function downloadAndExtractPdfJs() {
  console.log(`Downloading PDF.js v${PDFJS_VERSION}...`);
  await mkdir('public', { recursive: true });

  execSync(
    `curl -fL https://github.com/mozilla/pdf.js/releases/download/v${PDFJS_VERSION}/pdfjs-${PDFJS_VERSION}-dist.zip -o "${TEMP_ZIP}"`,
    { stdio: 'inherit' },
  );

  if (!existsSync(TEMP_ZIP)) {
    console.error(`Download failed: ${TEMP_ZIP} does not exist`);
    process.exit(1);
  }

  await mkdir(PDFJS_DIR, { recursive: true });
  if (isWindows) {
    execSync(`powershell -Command "Expand-Archive -Path '${TEMP_ZIP}' -DestinationPath '${PDFJS_DIR}' -Force"`, { stdio: 'inherit' });
  } else {
    execSync(`unzip -q "${TEMP_ZIP}" -d "${PDFJS_DIR}"`, { stdio: 'inherit' });
  }

  await rm(TEMP_ZIP);
  console.log('PDF.js installed successfully!');
}

/**
 * Emit a sibling viewer/index.html with <base href="/pdfjs/web/" /> so the
 * URL /pdfjs/web/viewer/ (trailing slash) serves the PDF.js viewer.
 *
 * Why: Astro's trailingSlash: 'always' setting can interfere with direct
 * serving of /pdfjs/web/viewer.html in dev mode for some Astro/Vite/OS
 * combinations. A trailing-slash directory route is unambiguous and always
 * serves correctly.
 *
 * Relative paths inside viewer.html (viewer.css, viewer.mjs, ../build/pdf.mjs)
 * remain valid because the <base> resets the resolution root.
 */
function ensureViewerIndexHtml() {
  if (!existsSync(VIEWER_HTML)) {
    console.warn(`Skipping viewer/index.html: ${VIEWER_HTML} not found`);
    return;
  }

  let src;
  try {
    src = readFileSync(VIEWER_HTML, 'utf-8');
  } catch (err) {
    console.warn(`Could not read ${VIEWER_HTML}: ${err.message}`);
    return;
  }

  const withBase = src.replace(
    /<head([^>]*)>/i,
    '<head$1>\n    <base href="/pdfjs/web/" />',
  );

  // Detect whether the existing index.html (if any) was generated by this
  // script. Re-emit if missing or if the source viewer.html has changed.
  let needsWrite = !existsSync(VIEWER_INDEX_HTML);
  if (!needsWrite) {
    try {
      const existing = readFileSync(VIEWER_INDEX_HTML, 'utf-8');
      needsWrite = existing !== withBase;
    } catch {
      needsWrite = true;
    }
  }

  if (!needsWrite) return;

  try {
    execSync(`mkdir -p "${VIEWER_INDEX_DIR}"`, { stdio: 'ignore' });
  } catch {
    // Fallback for Windows where mkdir -p may not be available.
    try { execSync(`powershell -Command "New-Item -ItemType Directory -Force -Path '${VIEWER_INDEX_DIR}'"`, { stdio: 'ignore' }); } catch { /* ignore */ }
  }
  writeFileSync(VIEWER_INDEX_HTML, withBase, 'utf-8');
  console.log(`Wrote ${VIEWER_INDEX_HTML} (with <base href>)`);
}

async function main() {
  if (existsSync(PDFJS_DIR)) {
    console.log('PDF.js already installed, ensuring viewer wrapper…');
  } else {
    await downloadAndExtractPdfJs();
  }
  ensureViewerIndexHtml();
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
